version: "3.3"
services:
    nginx:
        container_name: autoline-nginx
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - php
        volumes:
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    php:
        container_name: autoline-php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - .:/var/www/html
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    mysql:
        container_name: autoline-mysql
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'autoline'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'o251298'
            MYSQL_ROOT_PASSWORD: 'o251298root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./storage/db:/var/lib/mysql
            - .docker/mysql/mysql.conf:/etc/mysql/conf.d/custom.conf