<?php

namespace App\Console;

use App\Services\Redis\RedisClient;

class ClearQueue extends Command
{
    public function commandName(): void
    {
        $this->name = "queue:clear"; // TODO: Change the autogenerated stub
    }

    public function handle()
    {
        $redis = new RedisClient();
        print_r($redis->client->smembers('queue'));
        print "unset queue: " . PHP_EOL;
        if ($redis->client->del('queue')) print "success" . PHP_EOL;
        print_r($redis->client->smembers('queue'));
    }
}