<?php

namespace App\Console;

class MainQueueTest extends MainQueue
{

    public function commandName(): void
    {
        $this->name = "job:test"; // TODO: Change the autogenerated stub
    }

    public function handle()
    {
        while (true)
        {
            $childs = [];
            // Fork some process.
            $queue = $this->storeClient->client->smembers("queue");
            if (count($queue) > 0)
            {
                foreach ($queue as $class) {
                    $pid = pcntl_fork();
                    if($pid == -1)
                        die('Could not fork');
                    if ($pid) {
                        echo "parent \n";
                        $childs[] = $pid;
                    } else {
                        if (!class_exists($class)) throw new \Exception("Class not found");
                        $obj = new $class;
                        $obj->handle();
                        $this->storeClient->client->srem('queue', $class);
                        exit();
                    }
                }
                while(count($childs) > 0) {
                    foreach($childs as $key => $pid) {
                        $res = pcntl_waitpid($pid, $status, WNOHANG);
                        // If the process has already exited
                        if($res == -1 || $res > 0)
                            unset($childs[$key]);
                    }
                }

            } else {
                print "queue empty!" . PHP_EOL;
            }
            sleep(1);
        }
    }
}