<?php

namespace App\Console;

use App\Services\Redis\RedisClient;

class MainQueue extends Command
{
    protected RedisClient $storeClient;

    public function __construct($data = null)
    {
        parent::__construct($data);
        $this->storeClient = new RedisClient();
    }

    public function commandName(): void
    {
        $this->name = "job:start"; // TODO: Change the autogenerated stub
    }

    public function handle()
    {
        // getData from Redis
        //$this->storeClient->client->del('queue');
        //$queue = $this->storeClient->client->sadd("queue", ["\\App\\Jobs\\SendEmail", "\\App\\Jobs\\SaveUser", "\\App\\Jobs\\SavePost"]);
        $queue = $this->storeClient->client->smembers("queue");
        foreach ($queue as $class)
        {
            if (($pid=pcntl_fork())===-1)
            {
                continue;
            } else if ($pid)  {
                // Parent process
                pcntl_wait($status, WNOHANG); //protect against zombie children, one wait vs one child
            } else if ($pid===0) {
                // children process
                if (!class_exists($class)) throw new \Exception("Class not found");
                $obj = new $class;
                $obj->handle();
                exit();//avoid foreach loop in child process
            }
        }
    }
}