name: Deploy autoline
on:
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 185.65.246.209
        username: root
        key: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd autoline
          git pull origin master
